version: "3"

services:
  nginx:
    image: course_nginx:ver_1
    build:
      context: .
      dockerfile: ./docker/dev/nginx/Dockerfile_build
    ports:
      - 80:80

  php:
    image: course_php:ver_1
    build:
      context: .
      dockerfile: ./docker/dev/php/Dockerfile_build

  