version: "3"

services:
  nginx:
    image: nginx:1.14.0
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/app/web
      # - /var/run/php/php7.4-fpm.sock:/var/run/php/php7.4-fpm.sock

  php:
    build: ./docker/php
    # ports:
    #   - 9000:9000
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    # user: "1000:1000"

  redis:
    image: redis:4.0.9
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data
    command: '--appendonly yes'

  mongo:
    image: mongo:3.6.3
    # ports:
    #   - 27017:27017
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:10.12
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7.29
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  redis-data:
  mongodb-data:
  postgres-data:
  mysql-data: