FROM php:7.4.5-fpm


RUN apt-get update && apt-get install -y libpq-dev git zip unzip && apt-get clean 

RUN pecl install mongodb && \
	docker-php-ext-enable mongodb

RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql


RUN apt-get install curl && \
	curl -s https://getcomposer.org/installer | php && \
	mv composer.phar /usr/local/bin/composer

COPY ./ /var/www/app
WORKDIR /var/www/app

RUN composer install